apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mynginx
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  sources:
  - repoURL: https://github.com/knowre-junhyung-lee/argocd-test.git
    targetRevision: HEAD
    path: applications/mynginx
    helm:
      valueFiles:
      - $values
  - repoURL: 'https://github.com/knowre-junhyung-lee/argocd-helm-values.git'
    targetRevision: HEAD
    path: environments/develop/apne2/mynginx.yaml
    ref: values
    
  destination:
    server: https://kubernetes.default.svc
    namespace: mynginx
  
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true   
    # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.  
    syncOptions:
      - CreateNamespace=true   
